# Site settings
title: Fran.Kova.
domain: "frankovacevich.github.io"
baseurl: ""
url: "https://frankovacevich.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Francisco Kovacevich
  desc: Engineer / Developer
  email: frankovacevich@gmail.com
  selfie: assets/img/profile.png

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: frankova
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/fran-kova
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: _frankova
  vimeo:
  wordpress:
  youtube:
  default_txt: "Social Media"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/posts/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
